#!/bin/bash

cat <<-EOF

Vous pouvez lancer tout module dont vous avez precise le nom
Tapez <return> pour installer les modules, puis encore <return> pour les arreter
EOF

read junk
sudo insmod /usr/realtime/modules/rtai_hal.ko
sudo insmod /usr/realtime/modules/rtai_sched.ko
sudo insmod 3718.ko
sudo insmod 3712.ko
sudo insmod clcmat.ko
sudo insmod test_can.ko

lsmod
echo "Le programme fontionne"
echo "Tapez <return> pour l'arreter."
read junk

sudo rmmod test_can.ko
sudo rmmod clcmat
sudo rmmod 3712
sudo rmmod 3718
sudo rmmod rtai_sched
sudo rmmod rtai_hal
